import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer, { FooterContactSection } from "@/components/Footer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Bunon Texwear",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased bg-[#0B1746]`}>
        <Navbar />
        {children}
        <div
          className="w-full relative"
          style={{ height: "163px" /* half of 327px */ }}
        >
          <div
            className="absolute left-1/2 -translate-x-1/2"
            style={{
              top: "-163px", // negative half height to overlap
              width: "1062px",
              height: "327px",
              zIndex: 50,
            }}
          >
            <FooterContactSection />
          </div>
        </div>

        <Footer />
      </body>
    </html>
  );
}
