import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import FooterContactSwitcher from "@/components/FooterContactSwitcher";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Bunon Texwear",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased bg-[#0B1746]`}>
        <Navbar />
        {children}
        <div className="relative w-full flex justify-center min-h-[163px]">
          <div className="absolute left-1/2 -translate-x-1/2 w-full max-w-full md:max-w-[1062px] -top-[163px] z-50">
            <FooterContactSwitcher />
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
